spring:
  application:
    name: backEndForCursach
  datasource:
    url: jdbc:postgresql://localhost:7777/${MAIN_DB_NAME:dbName}
    password: ${MAIN_DB_PASSWORD:passwordForDb}
    username: ${MAIN_DB_USERNAME:usernameForDb}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/migrations.xml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
minio:
  endpoint: ${MINIO_ENDPOINT:miniEndpoint}
  access-key: ${MINIO_ACCESS_KEY:minioAccessKey}
  secret-key: ${MINIO_SECRET_KEY:minioSecretKey}
  bucket:
    images: ${MINIO_IMAGE_BUCKET:music-images}
    songs: ${MINIO_SONG_BUCKET:music-song}

jwt:
  token:
    expiration: 50
    secret: ${JWT_SECRET:secret}